try :
    print(x)
except NameError:
    print("execption happend")
except :
    print("something went wrong")